#!/usr/bin/env python

import os, sys, time

class condorSubmiter:
  def __init__(self,jobName) :
    self.time_ = time.strftime("_%d%b%Y_%HH%MM",time.localtime())
    self.runDir_ = jobName+self.time_
    self.jobName_ = jobName
    os.mkdir(self.runDir_)
    os.chdir(self.runDir_)
    self.tmpSub_ = """executable              = {sh}
universe                = vanilla
accounting_group        = group_cms
requirements            = ( HasSingularity == true )
max_transfer_output_mb  = 5000
request_memory          = 4G 
+SingularityImage       = "/cvmfs/singularity.opensciencegrid.org/opensciencegrid/osgvo-el6:latest"
+SingularityBind        = "/cvmfs, /cms, /share"
output                  = {shN}.out
error                   = {shN}.err
log                     = {shN}.log
transfer_input_files    = {inputs}
should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_output_files   = {outputs}
queue"""
    self.tmpSh_ = """#!/bin/bash
export MYPWD=`pwd`
tar -xf {tarBall}
rm {tarBall}
cd {cmsswSrc}
source /cvmfs/cms.cern.ch/cmsset_default.sh
eval `scramv1 runtime -sh`
cd $MYPWD
cmsRun {cfg} {runNum}
tar cf {out} *.root *.yoda"""

  def setInPuts(self, inPut):
    self.input_ = inPut
    self.tarBall_ = inPut[0]
    self.cfg_ = inPut[1]
    self.lhe_ = inPut[2]

  def setOutPuts(self, outPut):
    self.output_ = outPut

  def submit(self, jobNumber):
    shName = self.jobName_+"{:03}.sh".format(jobNumber)
    subName = self.jobName_+"{:03}.sub".format(jobNumber)
    shN = self.jobName_+"{:03}".format(jobNumber)
    out = "out{:03}.tar".format(jobNumber)
    tmpSh = open(shName, "w")
    tmpSh.write(self.tmpSh_.format(**{'tarBall':self.tarBall_.split("/")[-1],'cmsswSrc':self.tarBall_.split("/")[-1].replace(".tar","/src"),'cfg':self.cfg_.split("/")[-1], 'runNum':jobNumber,'out':out}))
    tmpSh.close()
    tmpSub = open(subName, "w")
    tmpSub.write(self.tmpSub_.format(**{'sh':shName, 'shN':shN, 'tarBall':self.tarBall_, 'inputs':', '.join(self.input_).format(jobNumber), 'outputs':out}))

    tmpSub.close()
    os.system("chmod +x "+shName)
    os.system("chmod +x "+subName)
    os.system("condor_submit -batch-name "+self.jobName_+" "+subName)

if __name__ == "__main__" :
  iPath = os.getcwd()
  lhePath = "/xrootd_user/hyunyong/xrootd/POWHEG8TeV"
  cs = condorSubmiter(sys.argv[1])
  cs.setInPuts([iPath+"/rivetRun.tar", iPath+"/QCD_powheg_v2_ct10_pytia8_cuetp8m1_rivet.py",lhePath+"/pwgeve_POWHEG2jet{:03}.lhe"]) 
  seedOffSet = 1
  for i in range(300):
    cs.submit(seedOffSet+i)


